### ISSUE TITLE
add two "multiagent-for-problem-solving" papers

### ISSUE THREAD

**Issue by zhouxh19** [taichengguo/LLM_MultiAgents_Survey_Papers#1]
Thanks for your wonderful survey! Here are two papers you may find relevant to the multi-agent topics :)

[1] "Llm as dba." arXiv preprint arXiv:2308.05481 (2023).

[2] "D-bot: Database diagnosis system using large language models." arXiv preprint arXiv:2312.01454 (2023).

**Comment by taichengguo** [comment]
Thanks for your attention to our work! The two papers you mentioned are very interesting. We will include these two papers in our repo and the next version of our survey.

@RuidiChang Please add these two papers to our repo first. Thanks.

**Comment by RuidiChang** [comment]
@zhouxh19 Thank you for recommending these two papers! We have added them into our repo.
@taichengguo Added. Thanks.
