### ISSUE TITLE
Introducing a paper on multi-agent

### ISSUE THREAD

**Issue by gearsuccess** [taichengguo/LLM_MultiAgents_Survey_Papers#2]

**Comment by gearsuccess** [comment]
Thanks for this important survey. 

I want to introduce you to a paper on multi-agent simulation entitled "User Behavior Simulation with Large Language Model-based Agents". 

Actually, this paper has been released on arxiv at 2023.6.5, which is earlier than many papers presented in the survey. 

Hope this paper can attract your attention.

Thanks

**Comment by taichengguo** [comment]
Thanks for your attention to our work! I have read this paper and the proposed user behavior simulator with LLM-based agents is very interesting! 

I have included this paper in our repo and will include it in the next version of our survey.

Thanks for your suggestions which make our survey more comprehensive!
