### ISSUE TITLE
Introducing a paper on LLM-based multi-agent system

### ISSUE THREAD

**Issue by binz98** [taichengguo/LLM_MultiAgents_Survey_Papers#3]
Thanks for your fantastic work! 
I'd like to share with you a paper that relevant to multi-agent systems:

"Controlling large language model-based agents for large-scale decision-making: An actor-critic approach." arXiv preprint arXiv:2311.13884 (2023).

**Comment by taichengguo** [comment]
Thanks for your attention to our work! 

I have read this paper and the proposed method for large-scale decision-making is very insightful. I remember I also read some insightful works from yours such as Tptu. 

I have included this paper in our repo and will include it in the next version of our survey. Thanks for your suggestions which make our survey more comprehensive.
